---
title: "Untitled"
date: today
format:
  html:
    css: style.css
    theme: flatly
    highlight-style: tango
---

```{r, include=FALSE}
library(tidyverse)
library(ggridges) # for ridge plots
library(patchwork) # optional, for combining plots
library(knitr)
library(kableExtra) # optional but makes it prettier
```

```{r, include=FALSE}
# Import humpback detection data with GIS calculations
hbk <- read_csv("data/GISCALC_HUWH_AroundSTX2025.csv")

# Import background mission data
bkg <- read_csv("data/erddap_UVI2_Around_STX_20250306.csv")
```

```{r, include=FALSE}
# Rename relevant columns in BKG df so variable names match detections (HBK) df
bkg <- bkg %>%
  rename(
    "Water_temperature_C" = "water_temperature",
    "Salinity_PSU" = "salinity",
    "Oxygen_concentration_µmol_L" = "oxygen_concentration"
  )
```

```{r, include=FALSE}
# Vector of environmental variables to summarize for background (*EXCLUDE glider depth because not really an environmental variable)
env_vars <- c(
  "Water_temperature_C",
  "Salinity_PSU",
  "Oxygen_concentration_µmol_L",
  "RASTERDEPTH_m",
  "RASTERSLOPE_deg",
  "NEAR_DIST"
  )
```

k

```{r, include=FALSE}
# Create DETECTIONS summary table dataframe
env_summary <- hbk %>%
  select(all_of(env_vars)) %>%
  pivot_longer(
    cols = everything(),
    names_to  = "Variable",
    values_to = "Value"
  ) %>%
  group_by(Variable) %>%
  summarise(
    n     = sum(!is.na(Value)),
    Mean  = mean(Value, na.rm = TRUE),
    SEM   = sd(Value, na.rm = TRUE) / sqrt(n),
    SD    = sd(Value, na.rm = TRUE),
    Min   = min(Value, na.rm = TRUE),
    Max   = max(Value, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(
    Variable = case_when(
      Variable == "Water_temperature_C" ~ "Water Temperature (°C)",
      Variable == "Salinity_PSU" ~ "Salinity (PSU)",
      Variable == "Oxygen_concentration_µmol_L" ~ "Dissolved Oxygen Concentration (µmol/L)",
      Variable == "RASTERDEPTH_m" ~ "Bathymetric Depth (m)",
      Variable == "RASTERSLOPE_deg" ~ "Bathymetric Slope (°)",
      Variable == "NEAR_DIST" ~ "Distance to Nearest Shoreline (m)",
      TRUE ~ Variable
    )
  )

# Reorder rows for table
env_summary <- env_summary %>%
  mutate(
    Variable = factor(
      Variable,
      levels = c(
        "Water Temperature (°C)",
        "Salinity (PSU)",
        "Dissolved Oxygen Concentration (µmol/L)",
        "Bathymetric Depth (m)",
        "Bathymetric Slope (°)",
        "Distance to Nearest Shoreline (m)"
      )
    )
  ) %>%
  arrange(Variable)
```

```{r, include=FALSE}
# Create BACKGROUND summary table dataframe
bkg_summary <- bkg %>%
  select("Water_temperature_C", "Salinity_PSU", "Oxygen_concentration_µmol_L") %>%
  pivot_longer(
    cols = everything(),
    names_to  = "Variable",
    values_to = "Value"
  ) %>%
  group_by(Variable) %>%
  summarise(
    n     = sum(!is.na(Value)),
    Mean  = mean(Value, na.rm = TRUE),
    SEM   = sd(Value, na.rm = TRUE) / sqrt(n),
    SD    = sd(Value, na.rm = TRUE),
    Min   = min(Value, na.rm = TRUE),
    Max   = max(Value, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(
    Variable = case_when(
      Variable == "Water_temperature_C" ~ "Water Temperature (°C)",
      Variable == "Salinity_PSU" ~ "Salinity (PSU)",
      Variable == "Oxygen_concentration_µmol_L" ~ "Dissolved Oxygen Concentration (µmol/L)",
      TRUE ~ Variable
    )
  )

# Reorder rows for table
bkg_summary <- bkg_summary %>%
  mutate(
    Variable = factor(
      Variable,
      levels = c(
        "Water Temperature (°C)",
        "Salinity (PSU)",
        "Dissolved Oxygen Concentration (µmol/L)"
      )
    )
  ) %>%
  arrange(Variable)
```

------------------------------------------------------------------------

```{r}
# Join env and background summaries by Variable
env_summary_diff <- env_summary %>%
  left_join(bkg_summary %>% 
              select(Variable, BKG_Mean = Mean), by = "Variable") %>%
  mutate(`Mean Difference from Background` = 
           sprintf("%+.5f", Mean - BKG_Mean))
```

```{r}
# Reorder columns and remove "n" and "Mean_bkg" columns (*do NOT need to add '%>% select(- "n", - "BKG_Mean")' because Mean_bkg not included in first select code line so already removed from df)
env_summary_table <- env_summary_diff %>%
  select("Variable", "Mean", "SEM", "SD", "Min", "Max", "Mean Difference from Background")
```

**Table 1.** \*WRITE CAPTION

```{r, echo=FALSE}
env_summary_table |>
  kable(format = "html", digits = 2) |>
  kable_styling(full_width = FALSE, bootstrap_options = c("striped", "hover"))
```
